[package]
name = "font-preview-plugin"
version = "4.0.1"
edition = "2024"
license = "MIT"

[lib]
name = "FontPreview"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
aviutl2 = "0"
aviutl2-eframe = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Imaging",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
windows-numerics = "0.3"

[profile.release]
lto = true
codegen-units = 1
strip = true
